from PyQt5.QtWidgets import *
import timing
import recorder
import sys

# main file mainly containing the GUI controls

rec = recorder.recorder()

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(836, 675)
        self.start = QtWidgets.QPushButton(Form)
        self.start.setGeometry(QtCore.QRect(530, 150, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.timealyze = QtWidgets.QPushButton(Form)
        self.timealyze.setGeometry(QtCore.QRect(510, 360, 171, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timealyze.setFont(font)
        self.timealyze.setObjectName("timealyze")
        self.dial = QtWidgets.QDial(Form)
        self.dial.setGeometry(QtCore.QRect(260, 20, 151, 131))
        self.dial.setMinimum(20)
        self.dial.setMaximum(300)
        self.dial.setSliderPosition(120)
        self.dial.setObjectName("dial")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 170, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stop = QtWidgets.QPushButton(Form)
        self.stop.setGeometry(QtCore.QRect(530, 220, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stop.setFont(font)
        self.stop.setObjectName("stop")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(540, 90, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.threshold_label = QtWidgets.QLabel(Form)
        self.threshold_label.setGeometry(QtCore.QRect(70, 320, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.threshold_label.setFont(font)
        self.threshold_label.setObjectName("threshold_label")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(70, 560, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.cappeaks = QtWidgets.QComboBox(Form)
        self.cappeaks.setGeometry(QtCore.QRect(230, 560, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cappeaks.setFont(font)
        self.cappeaks.setMouseTracking(False)
        self.cappeaks.setObjectName("cappeaks")
        self.cappeaks.addItem("")
        self.cappeaks.addItem("")
        self.threshold = QtWidgets.QSpinBox(Form)
        self.threshold.setGeometry(QtCore.QRect(260, 320, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.threshold.setFont(font)
        self.threshold.setMaximum(50000)
        self.threshold.setProperty("value", 5000)
        self.threshold.setObjectName("threshold")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(70, 390, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.deadzone = QtWidgets.QSpinBox(Form)
        self.deadzone.setGeometry(QtCore.QRect(260, 390, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deadzone.setFont(font)
        self.deadzone.setProperty("value", 5)
        self.deadzone.setObjectName("deadzone")
        self.subdivide = QtWidgets.QSpinBox(Form)
        self.subdivide.setGeometry(QtCore.QRect(260, 470, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.subdivide.setFont(font)
        self.subdivide.setMinimum(1)
        self.subdivide.setMaximum(4)
        self.subdivide.setProperty("value", 1)
        self.subdivide.setObjectName("subdivide")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(70, 470, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.offsetms = QtWidgets.QSpinBox(Form)
        self.offsetms.setGeometry(QtCore.QRect(260, 250, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.offsetms.setFont(font)
        self.offsetms.setMaximum(50000)
        self.offsetms.setProperty("value", 0)
        self.offsetms.setObjectName("offsetms")
        self.offset = QtWidgets.QLabel(Form)
        self.offset.setGeometry(QtCore.QRect(70, 250, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.offset.setFont(font)
        self.offset.setObjectName("offset")
        self.bpm = QtWidgets.QSpinBox(Form)
        self.bpm.setGeometry(QtCore.QRect(260, 180, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bpm.setFont(font)
        self.bpm.setMinimum(20)
        self.bpm.setMaximum(300)
        self.bpm.setProperty("value", 120)
        self.bpm.setObjectName("bpm")

        self.retranslateUi(Form)
        self.dial.valueChanged['int'].connect(self.bpm.setValue)
        self.bpm.valueChanged['int'].connect(self.dial.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.start.setText(_translate("Form", "start"))
        self.timealyze.setText(_translate("Form", "timealyze"))
        self.label.setText(_translate("Form", "tempo [bpm]"))
        self.stop.setText(_translate("Form", "stop"))
        self.label_4.setText(_translate("Form", "Recording"))
        self.threshold_label.setText(_translate("Form", "signal threshold"))
        self.label_6.setText(_translate("Form", "cap peaks"))
        self.cappeaks.setCurrentText(_translate("Form", "True"))
        self.cappeaks.setItemText(0, _translate("Form", "True"))
        self.cappeaks.setItemText(1, _translate("Form", "False"))
        self.label_7.setText(_translate("Form", "deadzone [%]"))
        self.label_8.setText(_translate("Form", "subdivide"))
        self.offset.setText(_translate("Form", "offset [ms]"))

    # insert adapted and added code here:

        self.timealyze.clicked.connect(self.click_timealyze)
        self.start.clicked.connect(self.click_record)
        self.stop.clicked.connect(self.click_stoprec)

    def click_record(self):
        rec.start()
        print("record clicked")

    def click_stoprec(self):
        rec.stop()
        print("recstop_clicked")
        rec.save("output.wav")

    def click_timealyze(self):
        bpm = int(self.bpm.text())
        offsetms = int(self.offsetms.value())
        threshold = int(self.threshold.value())
        deadzone = int(self.deadzone.value())
        subdiv = int(self.subdivide.value())
        cappeaks = bool(self.cappeaks.currentText())

        timing.timealyze(bpm, offsetms, threshold, deadzone, subdiv, cappeaks)
        print("timealyze clicked")

    # end adapted code


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())





