import timing
import recorder

# main file mainly containing the GUI controls

rec = recorder.recorder()

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(951, 752)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 40, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.bpm = QtWidgets.QSpinBox(self.centralwidget)
        self.bpm.setGeometry(QtCore.QRect(230, 50, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bpm.setFont(font)
        self.bpm.setMinimum(20)
        self.bpm.setMaximum(300)
        self.bpm.setProperty("value", 120)
        self.bpm.setObjectName("bpm")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(540, 100, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(490, 210, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.timealyze = QtWidgets.QPushButton(self.centralwidget)
        self.timealyze.setGeometry(QtCore.QRect(550, 270, 151, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timealyze.setFont(font)
        self.timealyze.setObjectName("timealyze")
        self.deadzone = QtWidgets.QSpinBox(self.centralwidget)
        self.deadzone.setGeometry(QtCore.QRect(250, 590, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deadzone.setFont(font)
        self.deadzone.setProperty("value", 5)
        self.deadzone.setObjectName("deadzone")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 230, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.eighth = QtWidgets.QRadioButton(self.centralwidget)
        self.eighth.setGeometry(QtCore.QRect(140, 290, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.eighth.setFont(font)
        self.eighth.setObjectName("eighth")
        self.numbeats = QtWidgets.QLabel(self.centralwidget)
        self.numbeats.setGeometry(QtCore.QRect(630, 640, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.numbeats.setFont(font)
        self.numbeats.setText("")
        self.numbeats.setAlignment(QtCore.Qt.AlignCenter)
        self.numbeats.setObjectName("numbeats")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(540, 30, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(540, 420, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.triplets = QtWidgets.QRadioButton(self.centralwidget)
        self.triplets.setGeometry(QtCore.QRect(240, 290, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.triplets.setFont(font)
        self.triplets.setObjectName("triplets")
        self.sixteenth = QtWidgets.QRadioButton(self.centralwidget)
        self.sixteenth.setGeometry(QtCore.QRect(340, 290, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sixteenth.setFont(font)
        self.sixteenth.setObjectName("sixteenth")
        self.quarter = QtWidgets.QRadioButton(self.centralwidget)
        self.quarter.setGeometry(QtCore.QRect(40, 290, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.quarter.setFont(font)
        self.quarter.setChecked(True)
        self.quarter.setObjectName("quarter")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(230, 100, 151, 131))
        self.dial.setMinimum(20)
        self.dial.setMaximum(300)
        self.dial.setSliderPosition(120)
        self.dial.setObjectName("dial")
        self.offset = QtWidgets.QLabel(self.centralwidget)
        self.offset.setGeometry(QtCore.QRect(40, 440, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.offset.setFont(font)
        self.offset.setObjectName("offset")
        self.showplot = QtWidgets.QPushButton(self.centralwidget)
        self.showplot.setGeometry(QtCore.QRect(740, 300, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showplot.setFont(font)
        self.showplot.setObjectName("showplot")
        self.offsetms = QtWidgets.QSpinBox(self.centralwidget)
        self.offsetms.setGeometry(QtCore.QRect(250, 450, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.offsetms.setFont(font)
        self.offsetms.setMaximum(50000)
        self.offsetms.setProperty("value", 0)
        self.offsetms.setObjectName("offsetms")
        self.threshold = QtWidgets.QSpinBox(self.centralwidget)
        self.threshold.setGeometry(QtCore.QRect(250, 520, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.threshold.setFont(font)
        self.threshold.setMaximum(50000)
        self.threshold.setProperty("value", 5000)
        self.threshold.setObjectName("threshold")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 580, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(560, 580, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.cappeaks = QtWidgets.QCheckBox(self.centralwidget)
        self.cappeaks.setGeometry(QtCore.QRect(10, 650, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cappeaks.setFont(font)
        self.cappeaks.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cappeaks.setAutoFillBackground(False)
        self.cappeaks.setChecked(True)
        self.cappeaks.setObjectName("cappeaks")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 380, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(720, 100, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stop.setFont(font)
        self.stop.setObjectName("stop")
        self.threshold_label = QtWidgets.QLabel(self.centralwidget)
        self.threshold_label.setGeometry(QtCore.QRect(40, 510, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.threshold_label.setFont(font)
        self.threshold_label.setObjectName("threshold_label")
        self.score = QtWidgets.QLabel(self.centralwidget)
        self.score.setGeometry(QtCore.QRect(610, 490, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.score.setFont(font)
        self.score.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"border-radius: 10px;\n"
"min-height: 40px;\n"
"min-width: 40px;")
        self.score.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.score.setFrameShadow(QtWidgets.QFrame.Raised)
        self.score.setText("")
        self.score.setAlignment(QtCore.Qt.AlignCenter)
        self.score.setObjectName("score")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(60, 350, 381, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(480, 50, 20, 641))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(540, 190, 331, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(890, 680, 55, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 951, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.bpm.valueChanged['int'].connect(self.dial.setValue)
        self.dial.valueChanged['int'].connect(self.bpm.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tempo [bpm]"))
        self.start.setText(_translate("MainWindow", "start"))
        self.label_6.setText(_translate("MainWindow", "Analyse"))
        self.timealyze.setText(_translate("MainWindow", "timealyze"))
        self.label_8.setText(_translate("MainWindow", "Rhythmusraster"))
        self.eighth.setText(_translate("MainWindow", "Achtel"))
        self.label_4.setText(_translate("MainWindow", "Aufnahme"))
        self.label_5.setText(_translate("MainWindow", "Timing Genauigkeit"))
        self.triplets.setText(_translate("MainWindow", "Triolen"))
        self.sixteenth.setText(_translate("MainWindow", "Sechzehntel"))
        self.quarter.setText(_translate("MainWindow", "Viertel"))
        self.offset.setText(_translate("MainWindow", "offset [ms]"))
        self.showplot.setText(_translate("MainWindow", "Show Plots"))
        self.label_7.setText(_translate("MainWindow", "deadzone [%]"))
        self.label_9.setText(_translate("MainWindow", "Anzahl erkannter Beats:"))
        self.cappeaks.setText(_translate("MainWindow", "Signalspitzen kappen                 "))
        self.label_2.setText(_translate("MainWindow", "Profi Einstellungen"))
        self.stop.setText(_translate("MainWindow", "stop"))
        self.threshold_label.setText(_translate("MainWindow", "Beat Erkennungsschwelle"))
        self.label_3.setText(_translate("MainWindow", "v1.1.2"))


        # insert adapted and added code here:
        self.statusbar.showMessage("Bereit")

        self.timealyze.clicked.connect(self.click_timealyze)
        self.start.clicked.connect(self.click_record)
        self.stop.clicked.connect(self.click_stoprec)
        self.showplot.clicked.connect(self.click_showplot)

    def click_showplot(self):
        timing.showplot()

    def click_record(self):
        rec.start()
        self.statusbar.showMessage("Aufnahme läuft...")
        print("record clicked")

    def click_stoprec(self):
        rec.stop()
        print("recstop_clicked")
        self.statusbar.showMessage("Aufnahme gestoppt. Speichert...")
        rec.save("output.wav")
        self.statusbar.showMessage('Bereit zum Auswerten. Klicke "timealyze!"')


    def click_timealyze(self):
        bpm = int(self.bpm.text())
        offsetms = int(self.offsetms.value())
        threshold = int(self.threshold.value())
        deadzone = int(self.deadzone.value())
        subdiv = 1 if self.quarter.isChecked() else 2 if self.eighth.isChecked() else 3 if self.triplets.isChecked() else 4 if self.sixteenth.isChecked() else 1
        cappeaks = True if self.cappeaks.isChecked() else False

        self.statusbar.showMessage("Timing wird berechnet...")

        sigmams, numbeats = timing.timealyze(bpm, offsetms, threshold, deadzone, subdiv, cappeaks)

        '''calculate the worst case deviation from a perfectly timed hit in ms. Note: divided by 2 because only relative
        timing is considered: more than half the time span of a note to late is rather too early for the next one.'''
        worstdiff = 60*1000/(subdiv*2*bpm)

        # calculate score. 100% is perfect timing. 50% means that on average the hits are 50% of worstdiff too late or too early
        score = (1 - sigmams/worstdiff) *100
        score = 0 if score < 0 else score

        #score = (100-0.7*(sigmams))

        #potential alternative function (probably need to import math package)
        #score = 30 * math.tanh((sigmams / 30) / sigmams)

        print("timealyze clicked")

        self.score.setText("{} %".format(str(round(score,2))))
        self.numbeats.setText(str(numbeats))

        self.statusbar.showMessage('Ergebnis liegt vor! Klicke "Show Plots" für eine detaillierte Auswertung')


    # end adapted code


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())





